name: mpd-ex
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - geopandas
  - jupyter_client<8
  - notebook
  - pandas
  - ipykernel
  - pip:
      - movingpandas
      - geoviews
      - hvplot
      - stonesoup
