name: mpd-ex
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - bokeh<3.0
  - cartopy
  - cython
  - esda
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jinja2<3.1
  - jupyterlab
  - matplotlib
  - movingpandas
  - networkx
  - numpy
  - osmnx
  - pandas
  - panel
  - proj
  - rasterio
  - scikit-learn
  - seaborn
  - shapely
  - spaghetti
  - splot
  - stonesoup
